feat: Dynamic content upload
UKForeignOffice/notarial-api pull request #30
Opened 2024-01-25 11:14 UTC by ziggy-cyb

Added dynamic content upload package so that we can add dynamic content from a csv to emails.

2024-01-25 11:40 UTC, jenbutongit requested changes

2024-01-25 11:40 UTC, jenbutongit commented on dynamic-content-upload/README.md
> +- `runner/src/server/forms-v3/cni.json`
this is running in a yarn workspace. are these commands / docs correct?

2024-01-25 11:40 UTC, jenbutongit commented on dynamic-content-upload/csv/booking-links.csv
> +Type,Country,Embassy,CABs link,Location number,https://www.book-consular-appointment.service.gov.uk/TimeSelection?location=,&service=10,&service=7,&service=13
column tidying discussed

2024-02-05 17:07 UTC, ziggy-cyb commented
- [ ]

2024-02-05 17:07 UTC, closed without merging